#!/bin/sh
# Auto-update CHANGELOG.md with each commit message

COMMIT_MSG=$(head -1 "$1")
DATE=$(date +%Y-%m-%d)

# Skip merge commits and automated changelog updates
case "$COMMIT_MSG" in
  Merge*|merge*) exit 0 ;;
esac

python3 -c "
import sys
msg = sys.argv[1]
date = sys.argv[2]
with open('CHANGELOG.md', 'r') as f:
    content = f.read()
new_entry = '- ' + date + ': ' + msg + '\n'
content = content.replace('## [Unreleased]\n', '## [Unreleased]\n' + new_entry, 1)
with open('CHANGELOG.md', 'w') as f:
    f.write(content)
" "$COMMIT_MSG" "$DATE"

git add CHANGELOG.md
